class_name LightLayer;

var ID:int
var NAME:String
var LIST_ITEM:VBoxContainer
var LIGHTS:Array[VertexLight]
var BLENDING_METHOD:BLENDING_METHODS
var BLENDING_DIRECTION:BLENDING_DIRECTIONS
var BLENDING_FADE:BLENDING_FADES
enum BLENDING_DIRECTIONS{
	EVERYTHING = 0,
	POINT_LIGHTS = 1,
	FACING_UP = 2,
	FACING_DOWN=3,
	INVERTED_POINT_LIGHT=4,
	DIRECTIONAL = 5,
	INVERSE_DIRECTIONAL
}
enum BLENDING_FADES{
	FLAT = 0,
	LINEAR_FADE = 1
}
enum BLENDING_METHODS{
	DEFAULT= 0,
	MULTIPLY= 1,
	ADD=2,
	SUBTRACT=3,
	DIVIDE=4,
	MIN=5,
	MAX=6,
	MIX=7,
	INVERTED_SUBTRACT=8,

}
