class_name LightLayer;

var ID:int
var NAME:String
var LIST_ITEM:VBoxContainer
var LIGHTS:Array[VertexLight]
var BLENDING_METHOD:BLENDING_METHODS
enum BLENDING_METHODS{
	DEFAULT= 0,
	MULTIPLY= 1,
	ADD=2,
	SUBTRACT=3,
	DIVIDE=4,
	MIN=5,
	MAX=6,
	MIX=7,#add flat
	MULTIPLY_FLAT= 8,
	SUBTRACT_FLAT=9,
	DIVIDE_FLAT=10,
	MIN_FLAT=11,
	MAX_FLAT=12,
}
